### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by digfish** [Kieran-Lock/SQLiteFrame#2]
Hi 

I'm trying to use your library, but on the first with the following code:
```python
from sqliteframe import table, Integer, String, ForeignKey,Database
database = Database('bep.sqlite',output=True,foreign_keys=True)
@table(db)
class Alert:
    id = Integer(primary_key=True)
    creation_date = String(nullable=False)
    last_update = String(nullable=False)
    search_term = String(nullable=False)

def main():
    insert_stmt = Offer.insert_into({
        'ref':'124',
        'tipo':'tipo'
    })
    insert_stmt.execute()

if __name__ == '__main__':
    main()
```

if fails on Windows in Python 3.10.4 (Anaconda) with the error:
```
Traceback (most recent call last):
  File "s:\bep_alerter\models.py", line 6, in <module>
    @table(database)
TypeError: 'module' object is not callable
```

**Comment by Kieran-Lock** [comment]
Hi @digfish 

This issue does not appear to be present in the snippet of code you have attached.
In the code you have attached, there a couple of issues though, which are hard to address without wider context:
* db is not defined, but you are passing it into the table decorator - perhaps you meant to write 'database' instead of 'db'?
* Offer is also not defined, but you are trying to build an insert into statement from it - I assume this is a table defined elsewhere in your program?

The actual error you have shown shows the line `@table(database)` from your `models.py` file. Could you please send me the content of that file so I can help you out further? It is likely that `database` is a module you have imported, and not an actual database object, but you are still passing it into the @table decorator, which it does not expect.

Thanks!

**Comment by digfish** [comment]
Hello @Kieran-Lock 
Thanks for your reply,

the complete snippet I'm using is below
```python
from sqliteframe import table, Integer, String, ForeignKey,Database

database = Database('bep0.sqlite',output=True,foreign_keys=True)

@table(database)
class Offer:
    id = Integer(primary_key=True)
    ref = String(nullable=False)
    tipo = String
    vinculo = String 
    carreira = String
    categoria = String
    distrito = String
    organismo = String
    habilitacoes = String 
    data_limite = String

@table(db)
class Alert:
    id = Integer(primary_key=True)
    creation_date = String(nullable=False)
    last_update = String(nullable=False)
    search_term = String(nullable=False)

@table('alert_offers')
class AlertOffer:
    id = Integer(primary_key=True)
    alert_id = ForeignKey(Alert,nullable=False)
    offer_id = ForeignKey(Offer,nullable=False)

def main():
    insert_stmt = Offer.insert_into({
        'ref':'124',
        'tipo':'tipo'
    })
    insert_stmt.execute()

if __name__ == '__main__':
    main()
```

> Hi @digfish
> 
> This issue does not appear to be present in the snippet of code you have attached. In the code you have attached, there a couple of issues though, which are hard to address without wider context:
> 
> * db is not defined, but you are passing it into the table decorator - perhaps you meant to write 'database' instead of 'db'?
> * Offer is also not defined, but you are trying to build an insert into statement from it - I assume this is a table defined elsewhere in your program?
> 
> The actual error you have shown shows the line `@table(database)` from your `models.py` file. Could you please send me the content of that file so I can help you out further? It is likely that `database` is a module you have imported, and not an actual database object, but you are still passing it into the @table decorator, which it does not expect.
> 
> Thanks!

**Comment by Kieran-Lock** [comment]
Okay - the code you gave has a couple of issues, so I will do my best to explain the changes you need to make, to make it function as I think you expect it to...


When I first run this code you have provided, I get the error:
```
    @table(db)
           ^^
NameError: name 'db' is not defined
```
The @table decorator requires a reference to the database object the table should belong to, so in this case, `@table(db)` should be `@table(database)`.

By the same logic, `@table('alert_offers')` should also be changed to `@table(database)`, as it belongs in the same database as the other tables. You are not passing a name for the table - you are passing a reference to the database the table is a member of.
  
  
The next issue I see is when you build the INSERT INTO statement - the data you pass in should not have the column names as strings, but as actual references to the columns. This would look like:
```py
insert_stmt = Offer.insert_into({
    Offer.ref: '124',
    Offer.tipo: 'tipo'
})
```
  
  
A third issue is that to execute commands to your database, a connection must be opened to the database. This can be done with a context manager:
```py
with database.connection():
    insert_stmt = Offer.insert_into({
        Offer.ref: '124',
        Offer.tipo: 'tipo'
    })
    insert_stmt.execute()
```
This will commit changes to the database at the end of the with statement by default, but you can opt out of this behaviour with `database.connection(commit=False)`, as `commit=True` is the default and does not need to be specified.
  
  
Finally, also note that when defining a table, `nullable` is `false` by default in each column declaration, and so does not need to be included - I am assuming therefore that the columns without `nullable` specified are supposed to be nullable, which means they should explicitly opt-in to this behaviour with `nullable=True`.

Now, your statement does not work, because no ID field is specified when inserting the data. I have extended the INSERT INTO statement to account for this with some draft data, but this should be changed as necessary:
```py
def main():
    with database.connection():
        insert_stmt = Offer.insert_into({
            Offer.id: 1234567890,
            Offer.ref: '124',
            Offer.tipo: 'tipo'
        })
        insert_stmt.execute()
```

On my version, having made these changes, this now works.
The full changes are as below:
```py
from sqliteframe import table, Integer, String, ForeignKey, Database


database = Database('bep0.sqlite', output=True, foreign_keys=True)


@table(database)
class Offer:
    id = Integer(primary_key=True)
    ref = String
    tipo = String(nullable=True)
    vinculo = String(nullable=True)
    carreira = String(nullable=True)
    categoria = String(nullable=True)
    distrito = String(nullable=True)
    organismo = String(nullable=True)
    habilitacoes = String(nullable=True)
    data_limite = String(nullable=True)


@table(database)
class Alert:
    id = Integer(primary_key=True)
    creation_date = String
    last_update = String
    search_term = String


@table(database)
class AlertOffer:
    id = Integer(primary_key=True)
    alert_id = ForeignKey(Alert)
    offer_id = ForeignKey(Offer)


def main():
    with database.connection():
        insert_stmt = Offer.insert_into({
            Offer.id: 1234567890,
            Offer.ref: '124',
            Offer.tipo: 'tipo'
        })
        insert_stmt.execute()


if __name__ == '__main__':
    main()
```

Can you confirm for me that this works for you? If you have any more questions don't hesitate to let me know!

**Comment by digfish** [comment]
Hi @Kieran-Lock ,

thanks for your extensive replay, at the start your code still didn't worked, until I figured by looking at your code in `__init__.py`:

```
from .database import Database
** from .table import Table **
from .types import Integer, String, Type, Boolean, Date, Time
from .wildcards import Wildcards
from .foreign_key import ForeignKey, Restraints as FKRestraints
from .result import Result
from .join import JoinTypes
from .order_by import OrderTypes
```
and then I changed all calls to `table` to `Table` and then it worked.

**Comment by Kieran-Lock** [comment]
@digfish 

Perhaps you are running on an older version of SQLiteFrame?
There has been a very recent update that I would recommend changing to - [v0.2.2-alpha](https://github.com/Kieran-Lock/SQLiteFrame/releases/tag/v0.2.2-alpha).

`table` should definitely be lowercase, as this is built as a decorator that will wrap your declared table classes so that they have all the necessary functionality to work with SQLiteFrame. `Table`, now called `Entity` in the latest version, should never really be accessed, and is internal - it cannot be used as a decorator in the same way as `table`.

Could you please double check you are using the latest version? Use `pip install SQLiteFrame --upgrade`, or `pip uninstall SQLiteFrame` followed by `pip install SQLiteFrame==0.2.2`.

Also, thanks for the feedback on documenting `database.connection()` - I will update this to make it clearer.

**Comment by Kieran-Lock** [comment]
Yes that's a small change I made in the latest update when creating the database, which allows for more flexible paths to be given.

```py
from sqliteframe import table, Integer, String, ForeignKey, Database


database = Database('bep.sqlite', output=True, foreign_keys=True)
```
should be changed to:
```py
from sqliteframe import table, Integer, String, ForeignKey, Database
from pathlib import Path


database = Database(Path('./bep.sqlite'), output=True, foreign_keys=True)
```

Following that everything should work as expected.
